select
       t.id,
       t.city_name,
       t.longitude,
       t.latitude,
       t.timezone,
       from_unixtime(t.timestamp,"%d.%m.%Y %h:%i:%s") timestamp,
       t.country,
       from_unixtime(t.sunrise_time,"%d.%m.%Y %h:%i:%s") sunrise_time,
       from_unixtime(t.sunset_time,"%d.%m.%Y %h:%i:%s") sunset_time,
       t.weather,
       t.weather_description,
       t.temperature,
       t.perceived_temperature,
       t.min_temperature,
       t.max_temperature,
       t.humidity,
       t.atmosphere_pressure,
       t.atmospheric_pressure_sea_level,
       t.atmospheric_pressure_ground_level,
       t.visibility,
       t.wind_speed,
       t.direction_wind,
       t.gust_wind,
       t.rain_volume_one_hour,
       t.rain_volume_three_hour,
       t.snow_volume_one_hour,
       t.snow_volume_three_hour,
       t.cloudiness
from openweather.weather_data t;